name: Move Files in OCR Directory

on:
  workflow_dispatch:

jobs:
  move-files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Move files within OCR directory
      run: |
        # נכנס לתיקיית OCR
        cd OCR
        
        # מעתיק את כל הקבצים מתיקיית המשנה לתיקיית OCR
        cp -r ocr-forms/* .
        
        # מוחק את תיקיית המשנה הריקה
        rm -rf ocr-forms
        
        # מציג את המבנה החדש
        echo "New OCR directory structure:"
        ls -la
        
    - name: Commit and push changes
      run: |
        # בדיקה אם יש שינויים
        if [[ -n "$(git status --porcelain)" ]]; then
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Moved files from OCR/ocr-forms to OCR directory"
          git push
          echo "Files moved successfully"
        else
          echo "No changes to commit"
        fi
